#include "VulkanNeuralExecutionPlan.h"
#include <algorithm>
namespace bncam::vulkan::neural { namespace {
bool has(const NeuralModelPackage&m,const std::string&n){return m.findTensor(n)!=nullptr;}
NeuralSlot other(NeuralSlot a,NeuralSlot b=NeuralSlot::Conditioning){for(auto s:{NeuralSlot::A,NeuralSlot::B,NeuralSlot::C})if(s!=a&&s!=b)return s;return NeuralSlot::C;}
void conv(NeuralExecutionPlan&p,NeuralSlot s,NeuralSlot d,const std::string&base,std::uint32_t ci,std::uint32_t co,std::uint32_t k,std::uint32_t stride,std::uint32_t div,bool up=false){p.ops.push_back({NeuralPrimitive::Conv,s,NeuralSlot::B,d,base+".weight",base+".bias","",ci,co,k,stride,div,up});}
NeuralSlot film(NeuralExecutionPlan&p,NeuralSlot cur,const std::string&base,std::uint32_t c,std::uint32_t div){auto d=other(cur);p.ops.push_back({NeuralPrimitive::Film,cur,NeuralSlot::Global,d,base+".film.proj.weight",base+".film.proj.bias","",18,c,1,1,div,false});return d;}
NeuralSlot block(NeuralExecutionPlan&p,NeuralSlot cur,const std::string&base,std::uint32_t c,std::uint32_t div){auto t1=other(cur);auto t2=other(cur,t1);conv(p,cur,t1,base+".mix_in",c,2*c,1,1,div);p.ops.push_back({NeuralPrimitive::SimpleGate,t1,NeuralSlot::B,t2,"","","",2*c,c,1,1,div,false});conv(p,t2,t1,base+".spatial",c,c,3,1,div);conv(p,t1,t2,base+".mix_out",c,c,1,1,div);p.ops.push_back({NeuralPrimitive::ScaledAdd,cur,t2,t1,"","",base+".beta",c,c,1,1,div,false});cur=t1;t1=other(cur);t2=other(cur,t1);conv(p,cur,t1,base+".ffn_in",c,2*c,1,1,div);p.ops.push_back({NeuralPrimitive::SimpleGate,t1,NeuralSlot::B,t2,"","","",2*c,c,1,1,div,false});conv(p,t2,t1,base+".ffn_out",c,c,1,1,div);p.ops.push_back({NeuralPrimitive::ScaledAdd,cur,t1,t2,"","",base+".gamma",c,c,1,1,div,false});return t2;}
bool validate(const NeuralModelPackage&m,const NeuralExecutionPlan&p){for(const auto&o:p.ops){if(!o.weight.empty()&&!has(m,o.weight))return false;if(!o.bias.empty()&&!has(m,o.bias))return false;if(!o.scale.empty()&&!has(m,o.scale))return false;if((o.primitive==NeuralPrimitive::Conv||o.primitive==NeuralPrimitive::SimpleGate||o.primitive==NeuralPrimitive::ScaledAdd||o.primitive==NeuralPrimitive::Add||o.primitive==NeuralPrimitive::Film)&&o.src0==o.dst)return false;}return true;}
}
NeuralExecutionPlan buildNeuralExecutionPlan(const NeuralModelPackage&m,std::uint32_t w,std::uint32_t h,std::uint32_t slots) noexcept{NeuralExecutionPlan p{};try{if(!m.valid||!w||!h||!slots||m.innerTile==0||m.halo*2u+1u<m.receptiveField){p.failureReason="NEURAL_PLAN_INPUT_INVALID";return p;}p.tiles=makeTileGeometry(w,h,m.innerTile,alignUp(m.halo,8u));p.tileCount=neuralTileCount(p.tiles);auto W=m.widths;p.maxChannels=std::max({m.inputChannels,W[0],W[1],W[2],W[3],2u*W[3]});p.ops.push_back({NeuralPrimitive::Conditioning,NeuralSlot::RawOriginal,NeuralSlot::Global,NeuralSlot::Conditioning,"","","",4,14,1,1,1,false});NeuralSlot cur=NeuralSlot::A;conv(p,NeuralSlot::Conditioning,cur,"stem",14,W[0],3,1,1);cur=film(p,cur,"enc0",W[0],1);for(std::uint32_t i=0;i<m.encoderBlocks[0];++i)cur=block(p,cur,"enc0.blocks."+std::to_string(i),W[0],1);p.ops.push_back({NeuralPrimitive::Copy,cur,NeuralSlot::B,NeuralSlot::Skip0,"","","",W[0],W[0],1,1,1,false});auto d=other(cur);conv(p,cur,d,"down0",W[0],W[1],3,2,2);cur=d;
cur=film(p,cur,"enc1",W[1],2);for(std::uint32_t i=0;i<m.encoderBlocks[1];++i)cur=block(p,cur,"enc1.blocks."+std::to_string(i),W[1],2);p.ops.push_back({NeuralPrimitive::Copy,cur,NeuralSlot::B,NeuralSlot::Skip1,"","","",W[1],W[1],1,1,2,false});d=other(cur);conv(p,cur,d,"down1",W[1],W[2],3,2,4);cur=d;
cur=film(p,cur,"enc2",W[2],4);for(std::uint32_t i=0;i<m.encoderBlocks[2];++i)cur=block(p,cur,"enc2.blocks."+std::to_string(i),W[2],4);p.ops.push_back({NeuralPrimitive::Copy,cur,NeuralSlot::B,NeuralSlot::Skip2,"","","",W[2],W[2],1,1,4,false});d=other(cur);conv(p,cur,d,"down2",W[2],W[3],3,2,8);cur=d;cur=film(p,cur,"bottleneck",W[3],8);for(std::uint32_t i=0;i<m.bottleneckBlocks;++i)cur=block(p,cur,"bottleneck.blocks."+std::to_string(i),W[3],8);
// Decoder nearest resize is fused into each up-convolution. Output divisor is the destination resolution.
d=other(cur);conv(p,cur,d,"up2",W[3],W[2],3,1,4,true);cur=d;d=other(cur);p.ops.push_back({NeuralPrimitive::Add,cur,NeuralSlot::Skip2,d,"","","",W[2],W[2],1,1,4,false});cur=d;cur=film(p,cur,"dec2",W[2],4);for(std::uint32_t i=0;i<m.decoderBlocks[0];++i)cur=block(p,cur,"dec2.blocks."+std::to_string(i),W[2],4);
d=other(cur);conv(p,cur,d,"up1",W[2],W[1],3,1,2,true);cur=d;d=other(cur);p.ops.push_back({NeuralPrimitive::Add,cur,NeuralSlot::Skip1,d,"","","",W[1],W[1],1,1,2,false});cur=d;cur=film(p,cur,"dec1",W[1],2);for(std::uint32_t i=0;i<m.decoderBlocks[1];++i)cur=block(p,cur,"dec1.blocks."+std::to_string(i),W[1],2);
d=other(cur);conv(p,cur,d,"up0",W[1],W[0],3,1,1,true);cur=d;d=other(cur);p.ops.push_back({NeuralPrimitive::Add,cur,NeuralSlot::Skip0,d,"","","",W[0],W[0],1,1,1,false});cur=d;cur=film(p,cur,"dec0",W[0],1);for(std::uint32_t i=0;i<m.decoderBlocks[2];++i)cur=block(p,cur,"dec0.blocks."+std::to_string(i),W[0],1);
conv(p,cur,NeuralSlot::ResidualLogits,"residual_head",W[0],4,3,1,1);conv(p,cur,NeuralSlot::PosteriorLogits,"posterior_head",W[0],4,3,1,1);if(m.flags&1u)conv(p,cur,NeuralSlot::ConfidenceLogits,"confidence_head",W[0],1,3,1,1);p.ops.push_back({NeuralPrimitive::Writeback,NeuralSlot::ResidualLogits,NeuralSlot::PosteriorLogits,NeuralSlot::CleanOutput,"","","",4,4,1,1,1,false});p.ops.push_back({NeuralPrimitive::Evidence,NeuralSlot::RawOriginal,NeuralSlot::Conditioning,NeuralSlot::EvidenceMask,"","","",4,1,1,1,1,false});if(!validate(m,p)){p.failureReason="NEURAL_PLAN_REQUIRED_TENSOR_OR_ALIAS_INVALID";return p;}p.kernelDispatchesPerTile=0;for(const auto&o:p.ops){if(o.primitive==NeuralPrimitive::Film)p.kernelDispatchesPerTile+=2u;else if(o.primitive!=NeuralPrimitive::Copy&&o.primitive!=NeuralPrimitive::Evidence)p.kernelDispatchesPerTile+=1u;}auto tw=p.tiles.tileInputWidth(),th=p.tiles.tileInputHeight();auto maxT=NeuralTensorShape{tw,th,p.maxChannels}.bytesFp16C4();auto skip0=NeuralTensorShape{tw,th,W[0]}.bytesFp16C4();auto skip1=NeuralTensorShape{ceilDiv(tw,2u),ceilDiv(th,2u),W[1]}.bytesFp16C4();auto skip2=NeuralTensorShape{ceilDiv(tw,4u),ceilDiv(th,4u),W[2]}.bytesFp16C4();auto cond=NeuralTensorShape{tw,th,14}.bytesFp16C4();auto logits=NeuralTensorShape{tw,th,12}.bytesFp16C4();auto filmP=std::uint64_t(ceilDiv(2u*W[3],4u))*8u;p.activationBytesPerSlot=cond+3u*maxT+skip0+skip1+skip2+logits+filmP+8192u;p.persistentArenaBytesPerSlot=p.activationBytesPerSlot*slots;p.valid=true;p.failureReason="none";return p;}catch(...){p.failureReason="NEURAL_PLAN_EXCEPTION";return p;}}
} // namespace bncam::vulkan::neural
