package com.bncam.core.quality

/** Milestone-6 temporal observer and correlation-aware fusion trace. */
data class SpectraTemporalFusionTrace(
    val architecture: String = "TEMPORAL_OBSERVER_2_CORRELATION_AWARE_FUSION",
    val staticMapMethod: String = "NORMALIZED_INNOVATION_BILINEAR_COARSE_FIELD",
    val fitMethod: String = "DUAL_WLS_HUBER_PHYSICAL_SELECTION",
    val fusionMethod: String = "LOCAL_STATIC_PROBABILITY_X_INVERSE_VARIANCE_X_CORRELATION",
    val persistence: String = "CAPTURE_LOCAL_NON_PERSISTENT",
    val enabled: Boolean = false,
    val observerOnly: Boolean = false,
    val acceptedFramePairs: Int = 0,
    val rejectedFramePairs: Int = 0,
    val forwardBackwardRejectedPairs: Int = 0,
    val observerSamples: Long = 0,
    val highConfidenceStaticSamples: Long = 0,
    val clippingRejectedSamples: Long = 0,
    val textureRejectedSamples: Long = 0,
    val localMotionRejectedSamples: Long = 0,
    val staticMapColumns: Int = 0,
    val staticMapRows: Int = 0,
    val staticMapCellSize: Int = 0,
    val alignmentConfidence: Double = 0.0,
    val motionConfidence: Double = 0.0,
    val observerConfidence: Double = 0.0,
    val forwardBackwardConsistency: Double = 0.0,
    val forwardBackwardConsistencyMin: Double = 0.0,
    val repeatedSupportConfidence: Double = 0.0,
    val staticProbabilityMean: Double = 0.0,
    val staticProbabilityP10: Double = 0.0,
    val staticProbabilityP50: Double = 0.0,
    val staticProbabilityP90: Double = 0.0,
    val normalizedInnovationMean: Double = 0.0,
    val normalizedInnovationVariance: Double = 0.0,
    val normalizedInnovationP90: Double = 0.0,
    val normalizedInnovationLagCorrelation: Double = 0.0,
    val heavyTailFraction: Double = 0.0,
    val temporalCorrelation: Double = 0.0,
    val persistentPatternFraction: Double = 0.0,
    val independentNoiseFraction: Double = 1.0,
    val fusionVarianceScale: Double = 1.0,
    val fusionVarianceP10: Double = 1.0,
    val fusionVarianceP50: Double = 1.0,
    val fusionVarianceP90: Double = 1.0,
    val effectiveFrameCount: Double = 1.0,
    val effectiveFrameCountP10: Double = 1.0,
    val effectiveFrameCountP50: Double = 1.0,
    val effectiveFrameCountP90: Double = 1.0,
    val localFusionFallbackFraction: Double = 1.0,
    val wlsSelectedChannels: Int = 0,
    val huberSelectedChannels: Int = 0,
    val fitStabilityConfidence: Double = 0.0,
    val fitStabilityMin: Double = 0.0,
    val fitStabilityByChannel: List<Double> = List(4) { 0.0 },
    val fitEstimator: List<Int> = List(4) { 0 },
    val fitPhysicalScore: List<Double> = List(4) { 0.0 },
    val fitInnovationMean: List<Double> = List(4) { 0.0 },
    val fitInnovationVariance: List<Double> = List(4) { 0.0 },
    val fitResidualCorrelation: List<Double> = List(4) { 0.0 },
    val fitHeavyTailFraction: List<Double> = List(4) { 0.0 },
    val forwardBackwardAlignmentMs: Double = 0.0,
    val temporalObserverMs: Double = 0.0,
    val staticConsensusMs: Double = 0.0,
    val fitConsensusMs: Double = 0.0,
    val correlationAnalysisMs: Double = 0.0
) {
    fun sanitized(): SpectraTemporalFusionTrace = copy(
        acceptedFramePairs = acceptedFramePairs.coerceAtLeast(0),
        rejectedFramePairs = rejectedFramePairs.coerceAtLeast(0),
        forwardBackwardRejectedPairs = forwardBackwardRejectedPairs.coerceAtLeast(0),
        observerSamples = observerSamples.coerceAtLeast(0),
        highConfidenceStaticSamples = highConfidenceStaticSamples.coerceAtLeast(0),
        clippingRejectedSamples = clippingRejectedSamples.coerceAtLeast(0),
        textureRejectedSamples = textureRejectedSamples.coerceAtLeast(0),
        localMotionRejectedSamples = localMotionRejectedSamples.coerceAtLeast(0),
        staticMapColumns = staticMapColumns.coerceAtLeast(0),
        staticMapRows = staticMapRows.coerceAtLeast(0),
        staticMapCellSize = staticMapCellSize.coerceAtLeast(0),
        alignmentConfidence = unitM6(alignmentConfidence),
        motionConfidence = unitM6(motionConfidence),
        observerConfidence = unitM6(observerConfidence),
        forwardBackwardConsistency = unitM6(forwardBackwardConsistency),
        forwardBackwardConsistencyMin = unitM6(forwardBackwardConsistencyMin),
        repeatedSupportConfidence = unitM6(repeatedSupportConfidence),
        staticProbabilityMean = unitM6(staticProbabilityMean),
        staticProbabilityP10 = unitM6(staticProbabilityP10),
        staticProbabilityP50 = unitM6(staticProbabilityP50),
        staticProbabilityP90 = unitM6(staticProbabilityP90),
        normalizedInnovationMean = finiteM6(normalizedInnovationMean),
        normalizedInnovationVariance = positiveM6(normalizedInnovationVariance),
        normalizedInnovationP90 = positiveM6(normalizedInnovationP90),
        normalizedInnovationLagCorrelation = finiteM6(normalizedInnovationLagCorrelation).coerceIn(-1.0, 1.0),
        heavyTailFraction = unitM6(heavyTailFraction),
        temporalCorrelation = unitM6(temporalCorrelation),
        persistentPatternFraction = unitM6(persistentPatternFraction),
        independentNoiseFraction = unitM6(independentNoiseFraction),
        fusionVarianceScale = positiveM6(fusionVarianceScale).coerceIn(0.02, 1.0),
        fusionVarianceP10 = positiveM6(fusionVarianceP10).coerceIn(0.02, 1.0),
        fusionVarianceP50 = positiveM6(fusionVarianceP50).coerceIn(0.02, 1.0),
        fusionVarianceP90 = positiveM6(fusionVarianceP90).coerceIn(0.02, 1.0),
        effectiveFrameCount = positiveM6(effectiveFrameCount).coerceAtLeast(1.0),
        effectiveFrameCountP10 = positiveM6(effectiveFrameCountP10).coerceAtLeast(1.0),
        effectiveFrameCountP50 = positiveM6(effectiveFrameCountP50).coerceAtLeast(1.0),
        effectiveFrameCountP90 = positiveM6(effectiveFrameCountP90).coerceAtLeast(1.0),
        localFusionFallbackFraction = unitM6(localFusionFallbackFraction),
        wlsSelectedChannels = wlsSelectedChannels.coerceIn(0, 4),
        huberSelectedChannels = huberSelectedChannels.coerceIn(0, 4),
        fitStabilityConfidence = unitM6(fitStabilityConfidence),
        fitStabilityMin = unitM6(fitStabilityMin),
        fitStabilityByChannel = fitStabilityByChannel.padM6(0.0).map(::unitM6),
        fitEstimator = fitEstimator.padM6(0).map { it.coerceIn(0, 2) },
        fitPhysicalScore = fitPhysicalScore.padM6(0.0).map(::unitM6),
        fitInnovationMean = fitInnovationMean.padM6(0.0).map(::finiteM6),
        fitInnovationVariance = fitInnovationVariance.padM6(0.0).map(::positiveM6),
        fitResidualCorrelation = fitResidualCorrelation.padM6(0.0).map { finiteM6(it).coerceIn(-1.0, 1.0) },
        fitHeavyTailFraction = fitHeavyTailFraction.padM6(0.0).map(::unitM6),
        forwardBackwardAlignmentMs = positiveM6(forwardBackwardAlignmentMs),
        temporalObserverMs = positiveM6(temporalObserverMs),
        staticConsensusMs = positiveM6(staticConsensusMs),
        fitConsensusMs = positiveM6(fitConsensusMs),
        correlationAnalysisMs = positiveM6(correlationAnalysisMs)
    )

    fun toTraceMap(): Map<String, Any> = sanitized().let { trace ->
        linkedMapOf(
            "architecture" to trace.architecture,
            "staticMapMethod" to trace.staticMapMethod,
            "fitMethod" to trace.fitMethod,
            "fusionMethod" to trace.fusionMethod,
            "persistence" to trace.persistence,
            "enabled" to trace.enabled,
            "observerOnly" to trace.observerOnly,
            "framePairs" to linkedMapOf(
                "accepted" to trace.acceptedFramePairs,
                "rejected" to trace.rejectedFramePairs,
                "forwardBackwardRejected" to trace.forwardBackwardRejectedPairs
            ),
            "staticProbability" to linkedMapOf(
                "mapColumns" to trace.staticMapColumns,
                "mapRows" to trace.staticMapRows,
                "cellSize" to trace.staticMapCellSize,
                "mean" to trace.staticProbabilityMean,
                "p10" to trace.staticProbabilityP10,
                "p50" to trace.staticProbabilityP50,
                "p90" to trace.staticProbabilityP90,
                "highConfidenceSamples" to trace.highConfidenceStaticSamples,
                "localMotionRejectedSamples" to trace.localMotionRejectedSamples,
                "clippingRejectedSamples" to trace.clippingRejectedSamples,
                "textureRejectedSamples" to trace.textureRejectedSamples
            ),
            "confidence" to linkedMapOf(
                "alignment" to trace.alignmentConfidence,
                "motion" to trace.motionConfidence,
                "observer" to trace.observerConfidence,
                "forwardBackward" to trace.forwardBackwardConsistency,
                "forwardBackwardMin" to trace.forwardBackwardConsistencyMin,
                "repeatedSupport" to trace.repeatedSupportConfidence
            ),
            "normalizedInnovation" to linkedMapOf(
                "mean" to trace.normalizedInnovationMean,
                "variance" to trace.normalizedInnovationVariance,
                "p90Absolute" to trace.normalizedInnovationP90,
                "lagCorrelation" to trace.normalizedInnovationLagCorrelation,
                "heavyTailFraction" to trace.heavyTailFraction,
                "samples" to trace.observerSamples
            ),
            "dualFit" to linkedMapOf(
                "wlsSelectedChannels" to trace.wlsSelectedChannels,
                "huberSelectedChannels" to trace.huberSelectedChannels,
                "stabilityConfidence" to trace.fitStabilityConfidence,
                "stabilityMin" to trace.fitStabilityMin,
                "stabilityByChannel" to trace.fitStabilityByChannel,
                "estimatorByChannel" to trace.fitEstimator,
                "physicalScoreByChannel" to trace.fitPhysicalScore,
                "innovationMeanByChannel" to trace.fitInnovationMean,
                "innovationVarianceByChannel" to trace.fitInnovationVariance,
                "residualCorrelationByChannel" to trace.fitResidualCorrelation,
                "heavyTailFractionByChannel" to trace.fitHeavyTailFraction
            ),
            "correlation" to linkedMapOf(
                "temporalCorrelation" to trace.temporalCorrelation,
                "persistentPatternFraction" to trace.persistentPatternFraction,
                "independentNoiseFraction" to trace.independentNoiseFraction
            ),
            "fusion" to linkedMapOf(
                "varianceScale" to trace.fusionVarianceScale,
                "varianceP10" to trace.fusionVarianceP10,
                "varianceP50" to trace.fusionVarianceP50,
                "varianceP90" to trace.fusionVarianceP90,
                "effectiveFrameCount" to trace.effectiveFrameCount,
                "effectiveFrameCountP10" to trace.effectiveFrameCountP10,
                "effectiveFrameCountP50" to trace.effectiveFrameCountP50,
                "effectiveFrameCountP90" to trace.effectiveFrameCountP90,
                "localFallbackFraction" to trace.localFusionFallbackFraction
            ),
            "timing" to linkedMapOf(
                "forwardBackwardAlignmentMs" to trace.forwardBackwardAlignmentMs,
                "temporalObserverMs" to trace.temporalObserverMs,
                "staticConsensusMs" to trace.staticConsensusMs,
                "fitConsensusMs" to trace.fitConsensusMs,
                "correlationAnalysisMs" to trace.correlationAnalysisMs,
                "accounting" to "NESTED_IN_NATIVE_MERGE_TOTAL"
            )
        )
    }

    companion object {
        fun fromNativeStats(stats: Map<String, String>): SpectraTemporalFusionTrace =
            SpectraTemporalFusionTrace(
                persistence = stats["spectraObserverPersistence"] ?: "CAPTURE_LOCAL_NON_PERSISTENT",
                enabled = stats.booleanM6("spectraEnabled"),
                observerOnly = stats.booleanM6("spectraObserverOnly"),
                acceptedFramePairs = stats.intM6("spectraAcceptedFramePairs"),
                rejectedFramePairs = stats.intM6("spectraRejectedFramePairs"),
                forwardBackwardRejectedPairs = stats.intM6("spectraForwardBackwardRejectedPairs"),
                observerSamples = stats.longM6("spectraObserverSamples"),
                highConfidenceStaticSamples = stats.longM6("spectraHighConfidenceStaticSamples"),
                clippingRejectedSamples = stats.longM6("spectraClippingRejectedSamples"),
                textureRejectedSamples = stats.longM6("spectraTextureRejectedSamples"),
                localMotionRejectedSamples = stats.longM6("spectraLocalMotionRejectedSamples"),
                staticMapColumns = stats.intM6("spectraStaticMapColumns"),
                staticMapRows = stats.intM6("spectraStaticMapRows"),
                staticMapCellSize = stats.intM6("spectraStaticMapCellSize"),
                alignmentConfidence = stats.numberM6("spectraAlignmentConfidence"),
                motionConfidence = stats.numberM6("spectraMotionConfidence"),
                observerConfidence = stats.numberM6("spectraObserverConfidence"),
                forwardBackwardConsistency = stats.numberM6("spectraForwardBackwardConsistency"),
                forwardBackwardConsistencyMin = stats.numberM6("spectraForwardBackwardConsistencyMin"),
                repeatedSupportConfidence = stats.numberM6("spectraRepeatedSupportConfidence"),
                staticProbabilityMean = stats.numberM6("spectraStaticProbabilityMean"),
                staticProbabilityP10 = stats.numberM6("spectraStaticProbabilityP10"),
                staticProbabilityP50 = stats.numberM6("spectraStaticProbabilityP50"),
                staticProbabilityP90 = stats.numberM6("spectraStaticProbabilityP90"),
                normalizedInnovationMean = stats.numberM6("spectraNormalizedInnovationMean"),
                normalizedInnovationVariance = stats.numberM6("spectraNormalizedInnovationVariance"),
                normalizedInnovationP90 = stats.numberM6("spectraNormalizedInnovationP90"),
                normalizedInnovationLagCorrelation = stats.numberM6("spectraNormalizedInnovationLagCorrelation"),
                heavyTailFraction = stats.numberM6("spectraHeavyTailFraction"),
                temporalCorrelation = stats.numberM6("spectraTemporalCorrelation"),
                persistentPatternFraction = stats.numberM6("spectraPersistentPatternFraction"),
                independentNoiseFraction = stats.numberM6("spectraIndependentNoiseFraction", 1.0),
                fusionVarianceScale = stats.numberM6("spectraFusionVarianceScale", 1.0),
                fusionVarianceP10 = stats.numberM6("spectraFusionVarianceP10", 1.0),
                fusionVarianceP50 = stats.numberM6("spectraFusionVarianceP50", 1.0),
                fusionVarianceP90 = stats.numberM6("spectraFusionVarianceP90", 1.0),
                effectiveFrameCount = stats.numberM6("spectraEffectiveFrameCount", 1.0),
                effectiveFrameCountP10 = stats.numberM6("spectraEffectiveFrameCountP10", 1.0),
                effectiveFrameCountP50 = stats.numberM6("spectraEffectiveFrameCountP50", 1.0),
                effectiveFrameCountP90 = stats.numberM6("spectraEffectiveFrameCountP90", 1.0),
                localFusionFallbackFraction = stats.numberM6("spectraLocalFusionFallbackFraction", 1.0),
                wlsSelectedChannels = stats.intM6("spectraWlsSelectedChannels"),
                huberSelectedChannels = stats.intM6("spectraHuberSelectedChannels"),
                fitStabilityConfidence = stats.numberM6("spectraFitStabilityConfidence"),
                fitStabilityMin = stats.numberM6("spectraFitStabilityMin"),
                fitStabilityByChannel = (0..3).map { stats.numberM6("spectraFitStability$it") },
                fitEstimator = (0..3).map { stats.intM6("spectraFitEstimator$it") },
                fitPhysicalScore = (0..3).map { stats.numberM6("spectraFitPhysicalScore$it") },
                fitInnovationMean = (0..3).map { stats.numberM6("spectraFitInnovationMean$it") },
                fitInnovationVariance = (0..3).map { stats.numberM6("spectraFitInnovationVariance$it") },
                fitResidualCorrelation = (0..3).map { stats.numberM6("spectraFitResidualCorrelation$it") },
                fitHeavyTailFraction = (0..3).map { stats.numberM6("spectraFitHeavyTailFraction$it") },
                forwardBackwardAlignmentMs = stats.numberM6("spectraForwardBackwardAlignmentMs"),
                temporalObserverMs = stats.numberM6("spectraTemporalObserverMs"),
                staticConsensusMs = stats.numberM6("spectraStaticConsensusMs"),
                fitConsensusMs = stats.numberM6("spectraFitConsensusMs"),
                correlationAnalysisMs = stats.numberM6("spectraCorrelationAnalysisMs")
            ).sanitized()
    }
}

private fun Map<String, String>.numberM6(key: String, fallback: Double = 0.0): Double =
    this[key]?.toDoubleOrNull()?.takeIf(Double::isFinite) ?: fallback

private fun Map<String, String>.intM6(key: String): Int = this[key]?.toIntOrNull() ?: 0
private fun Map<String, String>.longM6(key: String): Long = this[key]?.toLongOrNull() ?: 0L
private fun Map<String, String>.booleanM6(key: String): Boolean =
    this[key].equals("true", ignoreCase = true) || this[key].equals("yes", ignoreCase = true)

private fun finiteM6(value: Double): Double = if (value.isFinite()) value else 0.0
private fun positiveM6(value: Double): Double = finiteM6(value).coerceAtLeast(0.0)
private fun unitM6(value: Double): Double = finiteM6(value).coerceIn(0.0, 1.0)
private fun <T> List<T>.padM6(fallback: T): List<T> = List(4) { index -> getOrNull(index) ?: fallback }
